development:
  adapter: postgresql
  database: credport-2-development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: credport-2-test
  pool: 5
  timeout: 5000
production:
  adapter: postgresql
  database: credport-2-production
  pool: 5
  timeout: 5000